-- 005_auth.sql
-- Phase C: 真实认证与 RBAC 迁移
-- - 更新 admin 密码为真正 bcrypt hash
-- - 添加 must_change_password 列
-- - 添加 refresh_tokens 吊销列
-- - 统一角色枚举 (移除 operator, 新增 manager)
SET search_path TO assets;

-- 1. 更新现有 operator → manager (先改数据, 后改约束)
UPDATE assets.users SET role = 'manager' WHERE role = 'operator';

-- 2. 更新 admin 密码为 bcrypt('admin123')
-- hash generated by: bcrypt.GenerateFromPassword([]byte("admin123"), bcrypt.DefaultCost)
UPDATE assets.users
SET password_hash = '$2a$10$8obbmm6F.IYQ3a0GIzHAL.uyQzzVelSoXjXx/tpXnBLzFV3u4wxo6'
WHERE username = 'admin';

-- 3. must_change_password 列
ALTER TABLE assets.users
    ADD COLUMN IF NOT EXISTS must_change_password BOOLEAN NOT NULL DEFAULT false;

-- 4. refresh_tokens 吊销列
ALTER TABLE assets.refresh_tokens
    ADD COLUMN IF NOT EXISTS revoked_at TIMESTAMPTZ;

-- 5. 更新 role CHECK 约束
DO $$ BEGIN
    ALTER TABLE assets.users DROP CONSTRAINT IF EXISTS users_role_check;
    ALTER TABLE assets.users ADD CONSTRAINT users_role_check
        CHECK (role IN ('super_admin','admin','manager','viewer'));
EXCEPTION WHEN undefined_object THEN NULL; END $$;
